# Generated by Django 4.2.2 on 2023-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boredapi', '0002_activity_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='last_fetched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
